"""Model-facing inference boundary for ChartGround-Edit."""

from .mask_processing import (
    MaskProcessingError,
    MaskProcessingResult,
    process_prediction_masks,
)
from .metrics import (
    dice_score,
    empty_prediction,
    inference_success,
    intersection_over_union,
)
from .instruction_processing import (
    ACTION_PARAMETERS,
    ACTION_SUFFIXES,
    InstructionParts,
    InstructionProcessingError,
    extract_synthetic_v0_instruction,
)
from .prompt_diagnostic import (
    ACTION_ORDER,
    CHART_ORDER,
    REFERRING_ORDER,
    SPLIT_ORDER,
    SYNTHETIC_V1_SPLIT_PER_COMBINATION,
    audit_split_distribution,
    build_paired_results,
    organize_gallery_rows,
    summarize_prompt_variants,
    validate_diagnostic_split,
    validate_synthetic_v1_plan,
)
from .prompt_variants import (
    FULL_INSTRUCTION,
    PROMPT_TEMPLATES,
    PROMPT_VARIANT_ORDER,
    TARGET_ONLY_EN,
    TARGET_ONLY_ZH,
    build_prompt_variant,
    parse_prompt_variants,
)
from .sa2va_backend import (
    PROMPT_TEMPLATE,
    Sa2VAError,
    Sa2VAInternVL3Backend,
    Sa2VALoadError,
    build_prompt,
)
from .split_evaluation import (
    PredictionAttempt,
    SplitEvaluationError,
    binary_pixel_counts,
    gallery_status_label,
    is_global_failure,
    run_prediction_sequence,
    select_split_samples,
    summarize_results,
    write_summary_files,
)
from .types import PredictionResult

__all__ = [
    "ACTION_ORDER",
    "ACTION_PARAMETERS",
    "ACTION_SUFFIXES",
    "CHART_ORDER",
    "FULL_INSTRUCTION",
    "InstructionParts",
    "InstructionProcessingError",
    "MaskProcessingError",
    "MaskProcessingResult",
    "PROMPT_TEMPLATE",
    "PROMPT_TEMPLATES",
    "PROMPT_VARIANT_ORDER",
    "PredictionAttempt",
    "PredictionResult",
    "Sa2VAError",
    "Sa2VAInternVL3Backend",
    "Sa2VALoadError",
    "SplitEvaluationError",
    "SPLIT_ORDER",
    "SYNTHETIC_V1_SPLIT_PER_COMBINATION",
    "TARGET_ONLY_EN",
    "TARGET_ONLY_ZH",
    "audit_split_distribution",
    "binary_pixel_counts",
    "build_prompt",
    "build_prompt_variant",
    "build_paired_results",
    "dice_score",
    "empty_prediction",
    "extract_synthetic_v0_instruction",
    "gallery_status_label",
    "inference_success",
    "intersection_over_union",
    "is_global_failure",
    "process_prediction_masks",
    "parse_prompt_variants",
    "organize_gallery_rows",
    "run_prediction_sequence",
    "select_split_samples",
    "summarize_results",
    "summarize_prompt_variants",
    "validate_diagnostic_split",
    "validate_synthetic_v1_plan",
    "write_summary_files",
]
